// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/tcorp-bv/bol-api-go/client/commission"
	"github.com/tcorp-bv/bol-api-go/client/inbounds"
	"github.com/tcorp-bv/bol-api-go/client/insights"
	"github.com/tcorp-bv/bol-api-go/client/inventory"
	"github.com/tcorp-bv/bol-api-go/client/invoices"
	"github.com/tcorp-bv/bol-api-go/client/offers"
	"github.com/tcorp-bv/bol-api-go/client/orders"
	"github.com/tcorp-bv/bol-api-go/client/process_status"
	"github.com/tcorp-bv/bol-api-go/client/reductions"
	"github.com/tcorp-bv/bol-api-go/client/returns"
	"github.com/tcorp-bv/bol-api-go/client/shipments"
	"github.com/tcorp-bv/bol-api-go/client/shipping_labels"
	"github.com/tcorp-bv/bol-api-go/client/transports"
)

// Default v3 HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "api.bol.com"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"https"}

// NewHTTPClient creates a new v3 HTTP client.
func NewHTTPClient(formats strfmt.Registry) *V3 {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new v3 HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *V3 {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new v3 client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *V3 {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(V3)
	cli.Transport = transport
	cli.Commission = commission.New(transport, formats)
	cli.Inbounds = inbounds.New(transport, formats)
	cli.Insights = insights.New(transport, formats)
	cli.Inventory = inventory.New(transport, formats)
	cli.Invoices = invoices.New(transport, formats)
	cli.Offers = offers.New(transport, formats)
	cli.Orders = orders.New(transport, formats)
	cli.ProcessStatus = process_status.New(transport, formats)
	cli.Reductions = reductions.New(transport, formats)
	cli.Returns = returns.New(transport, formats)
	cli.Shipments = shipments.New(transport, formats)
	cli.ShippingLabels = shipping_labels.New(transport, formats)
	cli.Transports = transports.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// V3 is a client for v3
type V3 struct {
	Commission commission.ClientService

	Inbounds inbounds.ClientService

	Insights insights.ClientService

	Inventory inventory.ClientService

	Invoices invoices.ClientService

	Offers offers.ClientService

	Orders orders.ClientService

	ProcessStatus process_status.ClientService

	Reductions reductions.ClientService

	Returns returns.ClientService

	Shipments shipments.ClientService

	ShippingLabels shipping_labels.ClientService

	Transports transports.ClientService

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *V3) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.Commission.SetTransport(transport)
	c.Inbounds.SetTransport(transport)
	c.Insights.SetTransport(transport)
	c.Inventory.SetTransport(transport)
	c.Invoices.SetTransport(transport)
	c.Offers.SetTransport(transport)
	c.Orders.SetTransport(transport)
	c.ProcessStatus.SetTransport(transport)
	c.Reductions.SetTransport(transport)
	c.Returns.SetTransport(transport)
	c.Shipments.SetTransport(transport)
	c.ShippingLabels.SetTransport(transport)
	c.Transports.SetTransport(transport)
}
