// Code generated by go-swagger; DO NOT EDIT.

package reductions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetLatestReductionsFilenameReader is a Reader for the GetLatestReductionsFilename structure.
type GetLatestReductionsFilenameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLatestReductionsFilenameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetLatestReductionsFilenameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetLatestReductionsFilenameOK creates a GetLatestReductionsFilenameOK with default headers values
func NewGetLatestReductionsFilenameOK() *GetLatestReductionsFilenameOK {
	return &GetLatestReductionsFilenameOK{}
}

/*GetLatestReductionsFilenameOK handles this case with default header values.

Ok: Successfully processed the request.
*/
type GetLatestReductionsFilenameOK struct {
	Payload string
}

func (o *GetLatestReductionsFilenameOK) Error() string {
	return fmt.Sprintf("[GET /retailer/reductions/latest][%d] getLatestReductionsFilenameOK  %+v", 200, o.Payload)
}

func (o *GetLatestReductionsFilenameOK) GetPayload() string {
	return o.Payload
}

func (o *GetLatestReductionsFilenameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
