// Code generated by go-swagger; DO NOT EDIT.

package reductions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetLatestReductionsFilenameParams creates a new GetLatestReductionsFilenameParams object
// with the default values initialized.
func NewGetLatestReductionsFilenameParams() *GetLatestReductionsFilenameParams {

	return &GetLatestReductionsFilenameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetLatestReductionsFilenameParamsWithTimeout creates a new GetLatestReductionsFilenameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetLatestReductionsFilenameParamsWithTimeout(timeout time.Duration) *GetLatestReductionsFilenameParams {

	return &GetLatestReductionsFilenameParams{

		timeout: timeout,
	}
}

// NewGetLatestReductionsFilenameParamsWithContext creates a new GetLatestReductionsFilenameParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetLatestReductionsFilenameParamsWithContext(ctx context.Context) *GetLatestReductionsFilenameParams {

	return &GetLatestReductionsFilenameParams{

		Context: ctx,
	}
}

// NewGetLatestReductionsFilenameParamsWithHTTPClient creates a new GetLatestReductionsFilenameParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetLatestReductionsFilenameParamsWithHTTPClient(client *http.Client) *GetLatestReductionsFilenameParams {

	return &GetLatestReductionsFilenameParams{
		HTTPClient: client,
	}
}

/*GetLatestReductionsFilenameParams contains all the parameters to send to the API endpoint
for the get latest reductions filename operation typically these are written to a http.Request
*/
type GetLatestReductionsFilenameParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get latest reductions filename params
func (o *GetLatestReductionsFilenameParams) WithTimeout(timeout time.Duration) *GetLatestReductionsFilenameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get latest reductions filename params
func (o *GetLatestReductionsFilenameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get latest reductions filename params
func (o *GetLatestReductionsFilenameParams) WithContext(ctx context.Context) *GetLatestReductionsFilenameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get latest reductions filename params
func (o *GetLatestReductionsFilenameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get latest reductions filename params
func (o *GetLatestReductionsFilenameParams) WithHTTPClient(client *http.Client) *GetLatestReductionsFilenameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get latest reductions filename params
func (o *GetLatestReductionsFilenameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetLatestReductionsFilenameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
