// Code generated by go-swagger; DO NOT EDIT.

package reductions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetReductionsParams creates a new GetReductionsParams object
// with the default values initialized.
func NewGetReductionsParams() *GetReductionsParams {

	return &GetReductionsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetReductionsParamsWithTimeout creates a new GetReductionsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetReductionsParamsWithTimeout(timeout time.Duration) *GetReductionsParams {

	return &GetReductionsParams{

		timeout: timeout,
	}
}

// NewGetReductionsParamsWithContext creates a new GetReductionsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetReductionsParamsWithContext(ctx context.Context) *GetReductionsParams {

	return &GetReductionsParams{

		Context: ctx,
	}
}

// NewGetReductionsParamsWithHTTPClient creates a new GetReductionsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetReductionsParamsWithHTTPClient(client *http.Client) *GetReductionsParams {

	return &GetReductionsParams{
		HTTPClient: client,
	}
}

/*GetReductionsParams contains all the parameters to send to the API endpoint
for the get reductions operation typically these are written to a http.Request
*/
type GetReductionsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get reductions params
func (o *GetReductionsParams) WithTimeout(timeout time.Duration) *GetReductionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get reductions params
func (o *GetReductionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get reductions params
func (o *GetReductionsParams) WithContext(ctx context.Context) *GetReductionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get reductions params
func (o *GetReductionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get reductions params
func (o *GetReductionsParams) WithHTTPClient(client *http.Client) *GetReductionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get reductions params
func (o *GetReductionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetReductionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
