// Code generated by go-swagger; DO NOT EDIT.

package reductions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetReductionsReader is a Reader for the GetReductions structure.
type GetReductionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetReductionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetReductionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetReductionsOK creates a GetReductionsOK with default headers values
func NewGetReductionsOK() *GetReductionsOK {
	return &GetReductionsOK{}
}

/*GetReductionsOK handles this case with default header values.

Ok: Successfully processed the request.
*/
type GetReductionsOK struct {
}

func (o *GetReductionsOK) Error() string {
	return fmt.Sprintf("[GET /retailer/reductions][%d] getReductionsOK ", 200)
}

func (o *GetReductionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
