// Code generated by go-swagger; DO NOT EDIT.

package shipping_labels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetShippingLabelsParams creates a new GetShippingLabelsParams object
// with the default values initialized.
func NewGetShippingLabelsParams() *GetShippingLabelsParams {
	var ()
	return &GetShippingLabelsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetShippingLabelsParamsWithTimeout creates a new GetShippingLabelsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetShippingLabelsParamsWithTimeout(timeout time.Duration) *GetShippingLabelsParams {
	var ()
	return &GetShippingLabelsParams{

		timeout: timeout,
	}
}

// NewGetShippingLabelsParamsWithContext creates a new GetShippingLabelsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetShippingLabelsParamsWithContext(ctx context.Context) *GetShippingLabelsParams {
	var ()
	return &GetShippingLabelsParams{

		Context: ctx,
	}
}

// NewGetShippingLabelsParamsWithHTTPClient creates a new GetShippingLabelsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetShippingLabelsParamsWithHTTPClient(client *http.Client) *GetShippingLabelsParams {
	var ()
	return &GetShippingLabelsParams{
		HTTPClient: client,
	}
}

/*GetShippingLabelsParams contains all the parameters to send to the API endpoint
for the get shipping labels operation typically these are written to a http.Request
*/
type GetShippingLabelsParams struct {

	/*OrderItemID
	  The order item id of the order to get purchasable shipping labels from.

	*/
	OrderItemID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get shipping labels params
func (o *GetShippingLabelsParams) WithTimeout(timeout time.Duration) *GetShippingLabelsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get shipping labels params
func (o *GetShippingLabelsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get shipping labels params
func (o *GetShippingLabelsParams) WithContext(ctx context.Context) *GetShippingLabelsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get shipping labels params
func (o *GetShippingLabelsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get shipping labels params
func (o *GetShippingLabelsParams) WithHTTPClient(client *http.Client) *GetShippingLabelsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get shipping labels params
func (o *GetShippingLabelsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrderItemID adds the orderItemID to the get shipping labels params
func (o *GetShippingLabelsParams) WithOrderItemID(orderItemID string) *GetShippingLabelsParams {
	o.SetOrderItemID(orderItemID)
	return o
}

// SetOrderItemID adds the orderItemId to the get shipping labels params
func (o *GetShippingLabelsParams) SetOrderItemID(orderItemID string) {
	o.OrderItemID = orderItemID
}

// WriteToRequest writes these params to a swagger request
func (o *GetShippingLabelsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param order-item-id
	if err := r.SetPathParam("order-item-id", o.OrderItemID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
