// Code generated by go-swagger; DO NOT EDIT.

package shipping_labels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/tcorp-bv/bol-api-go/models"
)

// GetShippingLabelsReader is a Reader for the GetShippingLabels structure.
type GetShippingLabelsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetShippingLabelsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetShippingLabelsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetShippingLabelsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetShippingLabelsOK creates a GetShippingLabelsOK with default headers values
func NewGetShippingLabelsOK() *GetShippingLabelsOK {
	return &GetShippingLabelsOK{}
}

/*GetShippingLabelsOK handles this case with default header values.

Ok: Successfully processed the request.
*/
type GetShippingLabelsOK struct {
	Payload *models.PurchasableShippingLabelsResponse
}

func (o *GetShippingLabelsOK) Error() string {
	return fmt.Sprintf("[GET /retailer/purchasable-shippinglabels/{order-item-id}][%d] getShippingLabelsOK  %+v", 200, o.Payload)
}

func (o *GetShippingLabelsOK) GetPayload() *models.PurchasableShippingLabelsResponse {
	return o.Payload
}

func (o *GetShippingLabelsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PurchasableShippingLabelsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetShippingLabelsBadRequest creates a GetShippingLabelsBadRequest with default headers values
func NewGetShippingLabelsBadRequest() *GetShippingLabelsBadRequest {
	return &GetShippingLabelsBadRequest{}
}

/*GetShippingLabelsBadRequest handles this case with default header values.

Bad request: The sent request does not meet the API specification. Please check the error message(s) for more information.
*/
type GetShippingLabelsBadRequest struct {
	Payload *models.Problem
}

func (o *GetShippingLabelsBadRequest) Error() string {
	return fmt.Sprintf("[GET /retailer/purchasable-shippinglabels/{order-item-id}][%d] getShippingLabelsBadRequest  %+v", 400, o.Payload)
}

func (o *GetShippingLabelsBadRequest) GetPayload() *models.Problem {
	return o.Payload
}

func (o *GetShippingLabelsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Problem)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
