// Code generated by go-swagger; DO NOT EDIT.

package transports

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/tcorp-bv/bol-api-go/models"
)

// NewAddTransportInformationByTransportIDParams creates a new AddTransportInformationByTransportIDParams object
// with the default values initialized.
func NewAddTransportInformationByTransportIDParams() *AddTransportInformationByTransportIDParams {
	var ()
	return &AddTransportInformationByTransportIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAddTransportInformationByTransportIDParamsWithTimeout creates a new AddTransportInformationByTransportIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAddTransportInformationByTransportIDParamsWithTimeout(timeout time.Duration) *AddTransportInformationByTransportIDParams {
	var ()
	return &AddTransportInformationByTransportIDParams{

		timeout: timeout,
	}
}

// NewAddTransportInformationByTransportIDParamsWithContext creates a new AddTransportInformationByTransportIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewAddTransportInformationByTransportIDParamsWithContext(ctx context.Context) *AddTransportInformationByTransportIDParams {
	var ()
	return &AddTransportInformationByTransportIDParams{

		Context: ctx,
	}
}

// NewAddTransportInformationByTransportIDParamsWithHTTPClient creates a new AddTransportInformationByTransportIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAddTransportInformationByTransportIDParamsWithHTTPClient(client *http.Client) *AddTransportInformationByTransportIDParams {
	var ()
	return &AddTransportInformationByTransportIDParams{
		HTTPClient: client,
	}
}

/*AddTransportInformationByTransportIDParams contains all the parameters to send to the API endpoint
for the add transport information by transport id operation typically these are written to a http.Request
*/
type AddTransportInformationByTransportIDParams struct {

	/*Body
	  The change transport requested by the user.

	*/
	Body *models.ChangeTransportRequest
	/*TransportID
	  The transport id.

	*/
	TransportID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the add transport information by transport id params
func (o *AddTransportInformationByTransportIDParams) WithTimeout(timeout time.Duration) *AddTransportInformationByTransportIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add transport information by transport id params
func (o *AddTransportInformationByTransportIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add transport information by transport id params
func (o *AddTransportInformationByTransportIDParams) WithContext(ctx context.Context) *AddTransportInformationByTransportIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add transport information by transport id params
func (o *AddTransportInformationByTransportIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add transport information by transport id params
func (o *AddTransportInformationByTransportIDParams) WithHTTPClient(client *http.Client) *AddTransportInformationByTransportIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add transport information by transport id params
func (o *AddTransportInformationByTransportIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the add transport information by transport id params
func (o *AddTransportInformationByTransportIDParams) WithBody(body *models.ChangeTransportRequest) *AddTransportInformationByTransportIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the add transport information by transport id params
func (o *AddTransportInformationByTransportIDParams) SetBody(body *models.ChangeTransportRequest) {
	o.Body = body
}

// WithTransportID adds the transportID to the add transport information by transport id params
func (o *AddTransportInformationByTransportIDParams) WithTransportID(transportID int64) *AddTransportInformationByTransportIDParams {
	o.SetTransportID(transportID)
	return o
}

// SetTransportID adds the transportId to the add transport information by transport id params
func (o *AddTransportInformationByTransportIDParams) SetTransportID(transportID int64) {
	o.TransportID = transportID
}

// WriteToRequest writes these params to a swagger request
func (o *AddTransportInformationByTransportIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param transport-id
	if err := r.SetPathParam("transport-id", swag.FormatInt64(o.TransportID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
