// Code generated by go-swagger; DO NOT EDIT.

package transports

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/tcorp-bv/bol-api-go/models"
)

// AddTransportInformationByTransportIDReader is a Reader for the AddTransportInformationByTransportID structure.
type AddTransportInformationByTransportIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddTransportInformationByTransportIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewAddTransportInformationByTransportIDAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewAddTransportInformationByTransportIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewAddTransportInformationByTransportIDAccepted creates a AddTransportInformationByTransportIDAccepted with default headers values
func NewAddTransportInformationByTransportIDAccepted() *AddTransportInformationByTransportIDAccepted {
	return &AddTransportInformationByTransportIDAccepted{}
}

/*AddTransportInformationByTransportIDAccepted handles this case with default header values.

Accepted: Successfully scheduled the request for processing.
*/
type AddTransportInformationByTransportIDAccepted struct {
	Payload *models.ProcessStatus
}

func (o *AddTransportInformationByTransportIDAccepted) Error() string {
	return fmt.Sprintf("[PUT /retailer/transports/{transport-id}][%d] addTransportInformationByTransportIdAccepted  %+v", 202, o.Payload)
}

func (o *AddTransportInformationByTransportIDAccepted) GetPayload() *models.ProcessStatus {
	return o.Payload
}

func (o *AddTransportInformationByTransportIDAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProcessStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAddTransportInformationByTransportIDBadRequest creates a AddTransportInformationByTransportIDBadRequest with default headers values
func NewAddTransportInformationByTransportIDBadRequest() *AddTransportInformationByTransportIDBadRequest {
	return &AddTransportInformationByTransportIDBadRequest{}
}

/*AddTransportInformationByTransportIDBadRequest handles this case with default header values.

Bad request: The sent request does not meet the API specification. Please check the error message(s) for more information.
*/
type AddTransportInformationByTransportIDBadRequest struct {
	Payload *models.Problem
}

func (o *AddTransportInformationByTransportIDBadRequest) Error() string {
	return fmt.Sprintf("[PUT /retailer/transports/{transport-id}][%d] addTransportInformationByTransportIdBadRequest  %+v", 400, o.Payload)
}

func (o *AddTransportInformationByTransportIDBadRequest) GetPayload() *models.Problem {
	return o.Payload
}

func (o *AddTransportInformationByTransportIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Problem)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
