// Code generated by go-swagger; DO NOT EDIT.

package insights

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/tcorp-bv/bol-api-go/models"
)

// GetPerformanceIndicatorReader is a Reader for the GetPerformanceIndicator structure.
type GetPerformanceIndicatorReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPerformanceIndicatorReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPerformanceIndicatorOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetPerformanceIndicatorOK creates a GetPerformanceIndicatorOK with default headers values
func NewGetPerformanceIndicatorOK() *GetPerformanceIndicatorOK {
	return &GetPerformanceIndicatorOK{}
}

/*GetPerformanceIndicatorOK handles this case with default header values.

Ok: Successfully processed the request.
*/
type GetPerformanceIndicatorOK struct {
	Payload *models.PerformanceIndicators
}

func (o *GetPerformanceIndicatorOK) Error() string {
	return fmt.Sprintf("[GET /retailer/insights/performance/indicator][%d] getPerformanceIndicatorOK  %+v", 200, o.Payload)
}

func (o *GetPerformanceIndicatorOK) GetPayload() *models.PerformanceIndicators {
	return o.Payload
}

func (o *GetPerformanceIndicatorOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PerformanceIndicators)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
