// Code generated by go-swagger; DO NOT EDIT.

package invoices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/tcorp-bv/bol-api-go/models"
)

// GetInvoiceSpecificationReader is a Reader for the GetInvoiceSpecification structure.
type GetInvoiceSpecificationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetInvoiceSpecificationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetInvoiceSpecificationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetInvoiceSpecificationBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetInvoiceSpecificationOK creates a GetInvoiceSpecificationOK with default headers values
func NewGetInvoiceSpecificationOK() *GetInvoiceSpecificationOK {
	return &GetInvoiceSpecificationOK{}
}

/*GetInvoiceSpecificationOK handles this case with default header values.

Ok: Successfully processed the request.
*/
type GetInvoiceSpecificationOK struct {
	Payload []strfmt.Base64
}

func (o *GetInvoiceSpecificationOK) Error() string {
	return fmt.Sprintf("[GET /retailer/invoices/{invoice-id}/specification][%d] getInvoiceSpecificationOK  %+v", 200, o.Payload)
}

func (o *GetInvoiceSpecificationOK) GetPayload() []strfmt.Base64 {
	return o.Payload
}

func (o *GetInvoiceSpecificationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetInvoiceSpecificationBadRequest creates a GetInvoiceSpecificationBadRequest with default headers values
func NewGetInvoiceSpecificationBadRequest() *GetInvoiceSpecificationBadRequest {
	return &GetInvoiceSpecificationBadRequest{}
}

/*GetInvoiceSpecificationBadRequest handles this case with default header values.

Bad request: The sent request does not meet the API specification. Please check the error message(s) for more information.
*/
type GetInvoiceSpecificationBadRequest struct {
	Payload *models.Problem
}

func (o *GetInvoiceSpecificationBadRequest) Error() string {
	return fmt.Sprintf("[GET /retailer/invoices/{invoice-id}/specification][%d] getInvoiceSpecificationBadRequest  %+v", 400, o.Payload)
}

func (o *GetInvoiceSpecificationBadRequest) GetPayload() *models.Problem {
	return o.Payload
}

func (o *GetInvoiceSpecificationBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Problem)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
