// Code generated by go-swagger; DO NOT EDIT.

package invoices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetInvoiceSpecificationParams creates a new GetInvoiceSpecificationParams object
// with the default values initialized.
func NewGetInvoiceSpecificationParams() *GetInvoiceSpecificationParams {
	var ()
	return &GetInvoiceSpecificationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetInvoiceSpecificationParamsWithTimeout creates a new GetInvoiceSpecificationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetInvoiceSpecificationParamsWithTimeout(timeout time.Duration) *GetInvoiceSpecificationParams {
	var ()
	return &GetInvoiceSpecificationParams{

		timeout: timeout,
	}
}

// NewGetInvoiceSpecificationParamsWithContext creates a new GetInvoiceSpecificationParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetInvoiceSpecificationParamsWithContext(ctx context.Context) *GetInvoiceSpecificationParams {
	var ()
	return &GetInvoiceSpecificationParams{

		Context: ctx,
	}
}

// NewGetInvoiceSpecificationParamsWithHTTPClient creates a new GetInvoiceSpecificationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetInvoiceSpecificationParamsWithHTTPClient(client *http.Client) *GetInvoiceSpecificationParams {
	var ()
	return &GetInvoiceSpecificationParams{
		HTTPClient: client,
	}
}

/*GetInvoiceSpecificationParams contains all the parameters to send to the API endpoint
for the get invoice specification operation typically these are written to a http.Request
*/
type GetInvoiceSpecificationParams struct {

	/*InvoiceID
	  The id of the invoice.

	*/
	InvoiceID int64
	/*Page
	  The page to get. Each page contains a maximum of 110.000 lines.

	*/
	Page *int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get invoice specification params
func (o *GetInvoiceSpecificationParams) WithTimeout(timeout time.Duration) *GetInvoiceSpecificationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get invoice specification params
func (o *GetInvoiceSpecificationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get invoice specification params
func (o *GetInvoiceSpecificationParams) WithContext(ctx context.Context) *GetInvoiceSpecificationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get invoice specification params
func (o *GetInvoiceSpecificationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get invoice specification params
func (o *GetInvoiceSpecificationParams) WithHTTPClient(client *http.Client) *GetInvoiceSpecificationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get invoice specification params
func (o *GetInvoiceSpecificationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInvoiceID adds the invoiceID to the get invoice specification params
func (o *GetInvoiceSpecificationParams) WithInvoiceID(invoiceID int64) *GetInvoiceSpecificationParams {
	o.SetInvoiceID(invoiceID)
	return o
}

// SetInvoiceID adds the invoiceId to the get invoice specification params
func (o *GetInvoiceSpecificationParams) SetInvoiceID(invoiceID int64) {
	o.InvoiceID = invoiceID
}

// WithPage adds the page to the get invoice specification params
func (o *GetInvoiceSpecificationParams) WithPage(page *int32) *GetInvoiceSpecificationParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get invoice specification params
func (o *GetInvoiceSpecificationParams) SetPage(page *int32) {
	o.Page = page
}

// WriteToRequest writes these params to a swagger request
func (o *GetInvoiceSpecificationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param invoice-id
	if err := r.SetPathParam("invoice-id", swag.FormatInt64(o.InvoiceID)); err != nil {
		return err
	}

	if o.Page != nil {

		// query param page
		var qrPage int32
		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt32(qrPage)
		if qPage != "" {
			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
