// Code generated by go-swagger; DO NOT EDIT.

package invoices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/tcorp-bv/bol-api-go/models"
)

// GetInvoicesReader is a Reader for the GetInvoices structure.
type GetInvoicesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetInvoicesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetInvoicesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetInvoicesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetInvoicesOK creates a GetInvoicesOK with default headers values
func NewGetInvoicesOK() *GetInvoicesOK {
	return &GetInvoicesOK{}
}

/*GetInvoicesOK handles this case with default header values.

Ok: Successfully processed the request.
*/
type GetInvoicesOK struct {
	Payload []strfmt.Base64
}

func (o *GetInvoicesOK) Error() string {
	return fmt.Sprintf("[GET /retailer/invoices][%d] getInvoicesOK  %+v", 200, o.Payload)
}

func (o *GetInvoicesOK) GetPayload() []strfmt.Base64 {
	return o.Payload
}

func (o *GetInvoicesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetInvoicesBadRequest creates a GetInvoicesBadRequest with default headers values
func NewGetInvoicesBadRequest() *GetInvoicesBadRequest {
	return &GetInvoicesBadRequest{}
}

/*GetInvoicesBadRequest handles this case with default header values.

Bad request: The sent request does not meet the API specification. Please check the error message(s) for more information.
*/
type GetInvoicesBadRequest struct {
	Payload *models.Problem
}

func (o *GetInvoicesBadRequest) Error() string {
	return fmt.Sprintf("[GET /retailer/invoices][%d] getInvoicesBadRequest  %+v", 400, o.Payload)
}

func (o *GetInvoicesBadRequest) GetPayload() *models.Problem {
	return o.Payload
}

func (o *GetInvoicesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Problem)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
