// Code generated by go-swagger; DO NOT EDIT.

package process_status

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/tcorp-bv/bol-api-go/models"
)

// GetProcessStatusListReader is a Reader for the GetProcessStatusList structure.
type GetProcessStatusListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetProcessStatusListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetProcessStatusListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetProcessStatusListBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetProcessStatusListOK creates a GetProcessStatusListOK with default headers values
func NewGetProcessStatusListOK() *GetProcessStatusListOK {
	return &GetProcessStatusListOK{}
}

/*GetProcessStatusListOK handles this case with default header values.

Ok: Successfully processed the request.
*/
type GetProcessStatusListOK struct {
	Payload *models.ProcessStatusResponse
}

func (o *GetProcessStatusListOK) Error() string {
	return fmt.Sprintf("[GET /retailer/process-status][%d] getProcessStatusListOK  %+v", 200, o.Payload)
}

func (o *GetProcessStatusListOK) GetPayload() *models.ProcessStatusResponse {
	return o.Payload
}

func (o *GetProcessStatusListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProcessStatusResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProcessStatusListBadRequest creates a GetProcessStatusListBadRequest with default headers values
func NewGetProcessStatusListBadRequest() *GetProcessStatusListBadRequest {
	return &GetProcessStatusListBadRequest{}
}

/*GetProcessStatusListBadRequest handles this case with default header values.

Bad request: The sent request does not meet the API specification. Please check the error message(s) for more information.
*/
type GetProcessStatusListBadRequest struct {
	Payload *models.Problem
}

func (o *GetProcessStatusListBadRequest) Error() string {
	return fmt.Sprintf("[GET /retailer/process-status][%d] getProcessStatusListBadRequest  %+v", 400, o.Payload)
}

func (o *GetProcessStatusListBadRequest) GetPayload() *models.Problem {
	return o.Payload
}

func (o *GetProcessStatusListBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Problem)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
