// Code generated by go-swagger; DO NOT EDIT.

package process_status

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/tcorp-bv/bol-api-go/models"
)

// GetProcessStatusBulkReader is a Reader for the GetProcessStatusBulk structure.
type GetProcessStatusBulkReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetProcessStatusBulkReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetProcessStatusBulkOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetProcessStatusBulkBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetProcessStatusBulkOK creates a GetProcessStatusBulkOK with default headers values
func NewGetProcessStatusBulkOK() *GetProcessStatusBulkOK {
	return &GetProcessStatusBulkOK{}
}

/*GetProcessStatusBulkOK handles this case with default header values.

Ok: Successfully processed the request.
*/
type GetProcessStatusBulkOK struct {
	Payload *models.ProcessStatusResponse
}

func (o *GetProcessStatusBulkOK) Error() string {
	return fmt.Sprintf("[POST /retailer/process-status][%d] getProcessStatusBulkOK  %+v", 200, o.Payload)
}

func (o *GetProcessStatusBulkOK) GetPayload() *models.ProcessStatusResponse {
	return o.Payload
}

func (o *GetProcessStatusBulkOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProcessStatusResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProcessStatusBulkBadRequest creates a GetProcessStatusBulkBadRequest with default headers values
func NewGetProcessStatusBulkBadRequest() *GetProcessStatusBulkBadRequest {
	return &GetProcessStatusBulkBadRequest{}
}

/*GetProcessStatusBulkBadRequest handles this case with default header values.

Bad request: The sent request does not meet the API specification. Please check the error message(s) for more information.
*/
type GetProcessStatusBulkBadRequest struct {
	Payload *models.Problem
}

func (o *GetProcessStatusBulkBadRequest) Error() string {
	return fmt.Sprintf("[POST /retailer/process-status][%d] getProcessStatusBulkBadRequest  %+v", 400, o.Payload)
}

func (o *GetProcessStatusBulkBadRequest) GetPayload() *models.Problem {
	return o.Payload
}

func (o *GetProcessStatusBulkBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Problem)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
