// Code generated by go-swagger; DO NOT EDIT.

package process_status

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetProcessStatusParams creates a new GetProcessStatusParams object
// with the default values initialized.
func NewGetProcessStatusParams() *GetProcessStatusParams {
	var ()
	return &GetProcessStatusParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetProcessStatusParamsWithTimeout creates a new GetProcessStatusParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetProcessStatusParamsWithTimeout(timeout time.Duration) *GetProcessStatusParams {
	var ()
	return &GetProcessStatusParams{

		timeout: timeout,
	}
}

// NewGetProcessStatusParamsWithContext creates a new GetProcessStatusParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetProcessStatusParamsWithContext(ctx context.Context) *GetProcessStatusParams {
	var ()
	return &GetProcessStatusParams{

		Context: ctx,
	}
}

// NewGetProcessStatusParamsWithHTTPClient creates a new GetProcessStatusParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetProcessStatusParamsWithHTTPClient(client *http.Client) *GetProcessStatusParams {
	var ()
	return &GetProcessStatusParams{
		HTTPClient: client,
	}
}

/*GetProcessStatusParams contains all the parameters to send to the API endpoint
for the get process status operation typically these are written to a http.Request
*/
type GetProcessStatusParams struct {

	/*ProcessStatusID
	  The id of the process status being requested. This id is supplied in every response to a PUT/POST/DELETE request on the other endpoints.

	*/
	ProcessStatusID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get process status params
func (o *GetProcessStatusParams) WithTimeout(timeout time.Duration) *GetProcessStatusParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get process status params
func (o *GetProcessStatusParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get process status params
func (o *GetProcessStatusParams) WithContext(ctx context.Context) *GetProcessStatusParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get process status params
func (o *GetProcessStatusParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get process status params
func (o *GetProcessStatusParams) WithHTTPClient(client *http.Client) *GetProcessStatusParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get process status params
func (o *GetProcessStatusParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProcessStatusID adds the processStatusID to the get process status params
func (o *GetProcessStatusParams) WithProcessStatusID(processStatusID int64) *GetProcessStatusParams {
	o.SetProcessStatusID(processStatusID)
	return o
}

// SetProcessStatusID adds the processStatusId to the get process status params
func (o *GetProcessStatusParams) SetProcessStatusID(processStatusID int64) {
	o.ProcessStatusID = processStatusID
}

// WriteToRequest writes these params to a swagger request
func (o *GetProcessStatusParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param process-status-id
	if err := r.SetPathParam("process-status-id", swag.FormatInt64(o.ProcessStatusID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
