// Code generated by go-swagger; DO NOT EDIT.

package offers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/tcorp-bv/bol-api-go/models"
)

// DeleteOfferReader is a Reader for the DeleteOffer structure.
type DeleteOfferReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteOfferReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewDeleteOfferAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteOfferBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteOfferAccepted creates a DeleteOfferAccepted with default headers values
func NewDeleteOfferAccepted() *DeleteOfferAccepted {
	return &DeleteOfferAccepted{}
}

/*DeleteOfferAccepted handles this case with default header values.

Accepted: Successfully scheduled the request for processing.
*/
type DeleteOfferAccepted struct {
	Payload *models.ProcessStatus
}

func (o *DeleteOfferAccepted) Error() string {
	return fmt.Sprintf("[DELETE /retailer/offers/{offer-id}][%d] deleteOfferAccepted  %+v", 202, o.Payload)
}

func (o *DeleteOfferAccepted) GetPayload() *models.ProcessStatus {
	return o.Payload
}

func (o *DeleteOfferAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProcessStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteOfferBadRequest creates a DeleteOfferBadRequest with default headers values
func NewDeleteOfferBadRequest() *DeleteOfferBadRequest {
	return &DeleteOfferBadRequest{}
}

/*DeleteOfferBadRequest handles this case with default header values.

Bad request: The sent request does not meet the API specification. Please check the error message(s) for more information.
*/
type DeleteOfferBadRequest struct {
	Payload *models.Problem
}

func (o *DeleteOfferBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /retailer/offers/{offer-id}][%d] deleteOfferBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteOfferBadRequest) GetPayload() *models.Problem {
	return o.Payload
}

func (o *DeleteOfferBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Problem)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
