// Code generated by go-swagger; DO NOT EDIT.

package offers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteOfferParams creates a new DeleteOfferParams object
// with the default values initialized.
func NewDeleteOfferParams() *DeleteOfferParams {
	var ()
	return &DeleteOfferParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteOfferParamsWithTimeout creates a new DeleteOfferParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteOfferParamsWithTimeout(timeout time.Duration) *DeleteOfferParams {
	var ()
	return &DeleteOfferParams{

		timeout: timeout,
	}
}

// NewDeleteOfferParamsWithContext creates a new DeleteOfferParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteOfferParamsWithContext(ctx context.Context) *DeleteOfferParams {
	var ()
	return &DeleteOfferParams{

		Context: ctx,
	}
}

// NewDeleteOfferParamsWithHTTPClient creates a new DeleteOfferParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteOfferParamsWithHTTPClient(client *http.Client) *DeleteOfferParams {
	var ()
	return &DeleteOfferParams{
		HTTPClient: client,
	}
}

/*DeleteOfferParams contains all the parameters to send to the API endpoint
for the delete offer operation typically these are written to a http.Request
*/
type DeleteOfferParams struct {

	/*OfferID
	  Unique identifier for an offer.

	*/
	OfferID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete offer params
func (o *DeleteOfferParams) WithTimeout(timeout time.Duration) *DeleteOfferParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete offer params
func (o *DeleteOfferParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete offer params
func (o *DeleteOfferParams) WithContext(ctx context.Context) *DeleteOfferParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete offer params
func (o *DeleteOfferParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete offer params
func (o *DeleteOfferParams) WithHTTPClient(client *http.Client) *DeleteOfferParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete offer params
func (o *DeleteOfferParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOfferID adds the offerID to the delete offer params
func (o *DeleteOfferParams) WithOfferID(offerID string) *DeleteOfferParams {
	o.SetOfferID(offerID)
	return o
}

// SetOfferID adds the offerId to the delete offer params
func (o *DeleteOfferParams) SetOfferID(offerID string) {
	o.OfferID = offerID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteOfferParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param offer-id
	if err := r.SetPathParam("offer-id", o.OfferID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
