// Code generated by go-swagger; DO NOT EDIT.

package offers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetOfferExportParams creates a new GetOfferExportParams object
// with the default values initialized.
func NewGetOfferExportParams() *GetOfferExportParams {
	var ()
	return &GetOfferExportParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetOfferExportParamsWithTimeout creates a new GetOfferExportParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetOfferExportParamsWithTimeout(timeout time.Duration) *GetOfferExportParams {
	var ()
	return &GetOfferExportParams{

		timeout: timeout,
	}
}

// NewGetOfferExportParamsWithContext creates a new GetOfferExportParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetOfferExportParamsWithContext(ctx context.Context) *GetOfferExportParams {
	var ()
	return &GetOfferExportParams{

		Context: ctx,
	}
}

// NewGetOfferExportParamsWithHTTPClient creates a new GetOfferExportParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetOfferExportParamsWithHTTPClient(client *http.Client) *GetOfferExportParams {
	var ()
	return &GetOfferExportParams{
		HTTPClient: client,
	}
}

/*GetOfferExportParams contains all the parameters to send to the API endpoint
for the get offer export operation typically these are written to a http.Request
*/
type GetOfferExportParams struct {

	/*OfferExportID
	  Unique identifier for an offer export.

	*/
	OfferExportID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get offer export params
func (o *GetOfferExportParams) WithTimeout(timeout time.Duration) *GetOfferExportParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get offer export params
func (o *GetOfferExportParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get offer export params
func (o *GetOfferExportParams) WithContext(ctx context.Context) *GetOfferExportParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get offer export params
func (o *GetOfferExportParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get offer export params
func (o *GetOfferExportParams) WithHTTPClient(client *http.Client) *GetOfferExportParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get offer export params
func (o *GetOfferExportParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOfferExportID adds the offerExportID to the get offer export params
func (o *GetOfferExportParams) WithOfferExportID(offerExportID string) *GetOfferExportParams {
	o.SetOfferExportID(offerExportID)
	return o
}

// SetOfferExportID adds the offerExportId to the get offer export params
func (o *GetOfferExportParams) SetOfferExportID(offerExportID string) {
	o.OfferExportID = offerExportID
}

// WriteToRequest writes these params to a swagger request
func (o *GetOfferExportParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param offer-export-id
	if err := r.SetPathParam("offer-export-id", o.OfferExportID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
