// Code generated by go-swagger; DO NOT EDIT.

package offers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/tcorp-bv/bol-api-go/models"
)

// GetOfferExportReader is a Reader for the GetOfferExport structure.
type GetOfferExportReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetOfferExportReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetOfferExportOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetOfferExportBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetOfferExportNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetOfferExportOK creates a GetOfferExportOK with default headers values
func NewGetOfferExportOK() *GetOfferExportOK {
	return &GetOfferExportOK{}
}

/*GetOfferExportOK handles this case with default header values.

Ok: Successfully processed the request.
*/
type GetOfferExportOK struct {
}

func (o *GetOfferExportOK) Error() string {
	return fmt.Sprintf("[GET /retailer/offers/export/{offer-export-id}][%d] getOfferExportOK ", 200)
}

func (o *GetOfferExportOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetOfferExportBadRequest creates a GetOfferExportBadRequest with default headers values
func NewGetOfferExportBadRequest() *GetOfferExportBadRequest {
	return &GetOfferExportBadRequest{}
}

/*GetOfferExportBadRequest handles this case with default header values.

Bad request: The sent request does not meet the API specification. Please check the error message(s) for more information.
*/
type GetOfferExportBadRequest struct {
	Payload *models.Problem
}

func (o *GetOfferExportBadRequest) Error() string {
	return fmt.Sprintf("[GET /retailer/offers/export/{offer-export-id}][%d] getOfferExportBadRequest  %+v", 400, o.Payload)
}

func (o *GetOfferExportBadRequest) GetPayload() *models.Problem {
	return o.Payload
}

func (o *GetOfferExportBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Problem)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetOfferExportNotFound creates a GetOfferExportNotFound with default headers values
func NewGetOfferExportNotFound() *GetOfferExportNotFound {
	return &GetOfferExportNotFound{}
}

/*GetOfferExportNotFound handles this case with default header values.

Not found: The requested item could not be found.
*/
type GetOfferExportNotFound struct {
	Payload *models.Problem
}

func (o *GetOfferExportNotFound) Error() string {
	return fmt.Sprintf("[GET /retailer/offers/export/{offer-export-id}][%d] getOfferExportNotFound  %+v", 404, o.Payload)
}

func (o *GetOfferExportNotFound) GetPayload() *models.Problem {
	return o.Payload
}

func (o *GetOfferExportNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Problem)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
