// Code generated by go-swagger; DO NOT EDIT.

package offers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/tcorp-bv/bol-api-go/models"
)

// GetOfferReader is a Reader for the GetOffer structure.
type GetOfferReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetOfferReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetOfferOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetOfferNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetOfferOK creates a GetOfferOK with default headers values
func NewGetOfferOK() *GetOfferOK {
	return &GetOfferOK{}
}

/*GetOfferOK handles this case with default header values.

Ok: Successfully processed the request.
*/
type GetOfferOK struct {
	Payload *models.RetailerOffer
}

func (o *GetOfferOK) Error() string {
	return fmt.Sprintf("[GET /retailer/offers/{offer-id}][%d] getOfferOK  %+v", 200, o.Payload)
}

func (o *GetOfferOK) GetPayload() *models.RetailerOffer {
	return o.Payload
}

func (o *GetOfferOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RetailerOffer)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetOfferNotFound creates a GetOfferNotFound with default headers values
func NewGetOfferNotFound() *GetOfferNotFound {
	return &GetOfferNotFound{}
}

/*GetOfferNotFound handles this case with default header values.

Not found: The requested item could not be found.
*/
type GetOfferNotFound struct {
	Payload *models.Problem
}

func (o *GetOfferNotFound) Error() string {
	return fmt.Sprintf("[GET /retailer/offers/{offer-id}][%d] getOfferNotFound  %+v", 404, o.Payload)
}

func (o *GetOfferNotFound) GetPayload() *models.Problem {
	return o.Payload
}

func (o *GetOfferNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Problem)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
