// Code generated by go-swagger; DO NOT EDIT.

package offers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/tcorp-bv/bol-api-go/models"
)

// NewPostOfferParams creates a new PostOfferParams object
// with the default values initialized.
func NewPostOfferParams() *PostOfferParams {
	var ()
	return &PostOfferParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostOfferParamsWithTimeout creates a new PostOfferParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostOfferParamsWithTimeout(timeout time.Duration) *PostOfferParams {
	var ()
	return &PostOfferParams{

		timeout: timeout,
	}
}

// NewPostOfferParamsWithContext creates a new PostOfferParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostOfferParamsWithContext(ctx context.Context) *PostOfferParams {
	var ()
	return &PostOfferParams{

		Context: ctx,
	}
}

// NewPostOfferParamsWithHTTPClient creates a new PostOfferParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostOfferParamsWithHTTPClient(client *http.Client) *PostOfferParams {
	var ()
	return &PostOfferParams{
		HTTPClient: client,
	}
}

/*PostOfferParams contains all the parameters to send to the API endpoint
for the post offer operation typically these are written to a http.Request
*/
type PostOfferParams struct {

	/*Body*/
	Body *models.CreateOfferRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post offer params
func (o *PostOfferParams) WithTimeout(timeout time.Duration) *PostOfferParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post offer params
func (o *PostOfferParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post offer params
func (o *PostOfferParams) WithContext(ctx context.Context) *PostOfferParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post offer params
func (o *PostOfferParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post offer params
func (o *PostOfferParams) WithHTTPClient(client *http.Client) *PostOfferParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post offer params
func (o *PostOfferParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post offer params
func (o *PostOfferParams) WithBody(body *models.CreateOfferRequest) *PostOfferParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post offer params
func (o *PostOfferParams) SetBody(body *models.CreateOfferRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostOfferParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
