// Code generated by go-swagger; DO NOT EDIT.

package offers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/tcorp-bv/bol-api-go/models"
)

// PostOfferReader is a Reader for the PostOffer structure.
type PostOfferReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostOfferReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewPostOfferAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostOfferBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostOfferAccepted creates a PostOfferAccepted with default headers values
func NewPostOfferAccepted() *PostOfferAccepted {
	return &PostOfferAccepted{}
}

/*PostOfferAccepted handles this case with default header values.

Accepted: Successfully scheduled the request for processing.
*/
type PostOfferAccepted struct {
	Payload *models.ProcessStatus
}

func (o *PostOfferAccepted) Error() string {
	return fmt.Sprintf("[POST /retailer/offers][%d] postOfferAccepted  %+v", 202, o.Payload)
}

func (o *PostOfferAccepted) GetPayload() *models.ProcessStatus {
	return o.Payload
}

func (o *PostOfferAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProcessStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostOfferBadRequest creates a PostOfferBadRequest with default headers values
func NewPostOfferBadRequest() *PostOfferBadRequest {
	return &PostOfferBadRequest{}
}

/*PostOfferBadRequest handles this case with default header values.

Bad request: The sent request does not meet the API specification. Please check the error message(s) for more information.
*/
type PostOfferBadRequest struct {
	Payload *models.Problem
}

func (o *PostOfferBadRequest) Error() string {
	return fmt.Sprintf("[POST /retailer/offers][%d] postOfferBadRequest  %+v", 400, o.Payload)
}

func (o *PostOfferBadRequest) GetPayload() *models.Problem {
	return o.Payload
}

func (o *PostOfferBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Problem)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
