// Code generated by go-swagger; DO NOT EDIT.

package offers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/tcorp-bv/bol-api-go/models"
)

// PostOfferExportReader is a Reader for the PostOfferExport structure.
type PostOfferExportReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostOfferExportReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewPostOfferExportAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostOfferExportBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostOfferExportAccepted creates a PostOfferExportAccepted with default headers values
func NewPostOfferExportAccepted() *PostOfferExportAccepted {
	return &PostOfferExportAccepted{}
}

/*PostOfferExportAccepted handles this case with default header values.

Accepted: Successfully scheduled the request for processing.
*/
type PostOfferExportAccepted struct {
	Payload *models.ProcessStatus
}

func (o *PostOfferExportAccepted) Error() string {
	return fmt.Sprintf("[POST /retailer/offers/export][%d] postOfferExportAccepted  %+v", 202, o.Payload)
}

func (o *PostOfferExportAccepted) GetPayload() *models.ProcessStatus {
	return o.Payload
}

func (o *PostOfferExportAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProcessStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostOfferExportBadRequest creates a PostOfferExportBadRequest with default headers values
func NewPostOfferExportBadRequest() *PostOfferExportBadRequest {
	return &PostOfferExportBadRequest{}
}

/*PostOfferExportBadRequest handles this case with default header values.

Bad request: The sent request does not meet the API specification. Please check the error message(s) for more information.
*/
type PostOfferExportBadRequest struct {
	Payload *models.Problem
}

func (o *PostOfferExportBadRequest) Error() string {
	return fmt.Sprintf("[POST /retailer/offers/export][%d] postOfferExportBadRequest  %+v", 400, o.Payload)
}

func (o *PostOfferExportBadRequest) GetPayload() *models.Problem {
	return o.Payload
}

func (o *PostOfferExportBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Problem)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
