// Code generated by go-swagger; DO NOT EDIT.

package offers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/tcorp-bv/bol-api-go/models"
)

// PutOfferReader is a Reader for the PutOffer structure.
type PutOfferReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutOfferReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewPutOfferAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPutOfferBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutOfferAccepted creates a PutOfferAccepted with default headers values
func NewPutOfferAccepted() *PutOfferAccepted {
	return &PutOfferAccepted{}
}

/*PutOfferAccepted handles this case with default header values.

Accepted: Successfully scheduled the request for processing.
*/
type PutOfferAccepted struct {
	Payload *models.ProcessStatus
}

func (o *PutOfferAccepted) Error() string {
	return fmt.Sprintf("[PUT /retailer/offers/{offer-id}][%d] putOfferAccepted  %+v", 202, o.Payload)
}

func (o *PutOfferAccepted) GetPayload() *models.ProcessStatus {
	return o.Payload
}

func (o *PutOfferAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProcessStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutOfferBadRequest creates a PutOfferBadRequest with default headers values
func NewPutOfferBadRequest() *PutOfferBadRequest {
	return &PutOfferBadRequest{}
}

/*PutOfferBadRequest handles this case with default header values.

Bad request: The sent request does not meet the API specification. Please check the error message(s) for more information.
*/
type PutOfferBadRequest struct {
	Payload *models.Problem
}

func (o *PutOfferBadRequest) Error() string {
	return fmt.Sprintf("[PUT /retailer/offers/{offer-id}][%d] putOfferBadRequest  %+v", 400, o.Payload)
}

func (o *PutOfferBadRequest) GetPayload() *models.Problem {
	return o.Payload
}

func (o *PutOfferBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Problem)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
