// Code generated by go-swagger; DO NOT EDIT.

package offers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/tcorp-bv/bol-api-go/models"
)

// UpdateOfferStockReader is a Reader for the UpdateOfferStock structure.
type UpdateOfferStockReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateOfferStockReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewUpdateOfferStockAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpdateOfferStockBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateOfferStockAccepted creates a UpdateOfferStockAccepted with default headers values
func NewUpdateOfferStockAccepted() *UpdateOfferStockAccepted {
	return &UpdateOfferStockAccepted{}
}

/*UpdateOfferStockAccepted handles this case with default header values.

Accepted: Successfully scheduled the request for processing.
*/
type UpdateOfferStockAccepted struct {
	Payload *models.ProcessStatus
}

func (o *UpdateOfferStockAccepted) Error() string {
	return fmt.Sprintf("[PUT /retailer/offers/{offer-id}/stock][%d] updateOfferStockAccepted  %+v", 202, o.Payload)
}

func (o *UpdateOfferStockAccepted) GetPayload() *models.ProcessStatus {
	return o.Payload
}

func (o *UpdateOfferStockAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProcessStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateOfferStockBadRequest creates a UpdateOfferStockBadRequest with default headers values
func NewUpdateOfferStockBadRequest() *UpdateOfferStockBadRequest {
	return &UpdateOfferStockBadRequest{}
}

/*UpdateOfferStockBadRequest handles this case with default header values.

Bad request: The sent request does not meet the API specification. Please check the error message(s) for more information.
*/
type UpdateOfferStockBadRequest struct {
	Payload *models.Problem
}

func (o *UpdateOfferStockBadRequest) Error() string {
	return fmt.Sprintf("[PUT /retailer/offers/{offer-id}/stock][%d] updateOfferStockBadRequest  %+v", 400, o.Payload)
}

func (o *UpdateOfferStockBadRequest) GetPayload() *models.Problem {
	return o.Payload
}

func (o *UpdateOfferStockBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Problem)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
