// Code generated by go-swagger; DO NOT EDIT.

package offers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/tcorp-bv/bol-api-go/models"
)

// NewUpdateOfferPriceParams creates a new UpdateOfferPriceParams object
// with the default values initialized.
func NewUpdateOfferPriceParams() *UpdateOfferPriceParams {
	var ()
	return &UpdateOfferPriceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateOfferPriceParamsWithTimeout creates a new UpdateOfferPriceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateOfferPriceParamsWithTimeout(timeout time.Duration) *UpdateOfferPriceParams {
	var ()
	return &UpdateOfferPriceParams{

		timeout: timeout,
	}
}

// NewUpdateOfferPriceParamsWithContext creates a new UpdateOfferPriceParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateOfferPriceParamsWithContext(ctx context.Context) *UpdateOfferPriceParams {
	var ()
	return &UpdateOfferPriceParams{

		Context: ctx,
	}
}

// NewUpdateOfferPriceParamsWithHTTPClient creates a new UpdateOfferPriceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateOfferPriceParamsWithHTTPClient(client *http.Client) *UpdateOfferPriceParams {
	var ()
	return &UpdateOfferPriceParams{
		HTTPClient: client,
	}
}

/*UpdateOfferPriceParams contains all the parameters to send to the API endpoint
for the update offer price operation typically these are written to a http.Request
*/
type UpdateOfferPriceParams struct {

	/*Body*/
	Body *models.UpdateOfferPriceRequest
	/*OfferID
	  Unique identifier for an offer.

	*/
	OfferID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update offer price params
func (o *UpdateOfferPriceParams) WithTimeout(timeout time.Duration) *UpdateOfferPriceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update offer price params
func (o *UpdateOfferPriceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update offer price params
func (o *UpdateOfferPriceParams) WithContext(ctx context.Context) *UpdateOfferPriceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update offer price params
func (o *UpdateOfferPriceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update offer price params
func (o *UpdateOfferPriceParams) WithHTTPClient(client *http.Client) *UpdateOfferPriceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update offer price params
func (o *UpdateOfferPriceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update offer price params
func (o *UpdateOfferPriceParams) WithBody(body *models.UpdateOfferPriceRequest) *UpdateOfferPriceParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update offer price params
func (o *UpdateOfferPriceParams) SetBody(body *models.UpdateOfferPriceRequest) {
	o.Body = body
}

// WithOfferID adds the offerID to the update offer price params
func (o *UpdateOfferPriceParams) WithOfferID(offerID string) *UpdateOfferPriceParams {
	o.SetOfferID(offerID)
	return o
}

// SetOfferID adds the offerId to the update offer price params
func (o *UpdateOfferPriceParams) SetOfferID(offerID string) {
	o.OfferID = offerID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateOfferPriceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param offer-id
	if err := r.SetPathParam("offer-id", o.OfferID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
