// Code generated by go-swagger; DO NOT EDIT.

package offers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/tcorp-bv/bol-api-go/models"
)

// UpdateOfferPriceReader is a Reader for the UpdateOfferPrice structure.
type UpdateOfferPriceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateOfferPriceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewUpdateOfferPriceAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpdateOfferPriceBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateOfferPriceAccepted creates a UpdateOfferPriceAccepted with default headers values
func NewUpdateOfferPriceAccepted() *UpdateOfferPriceAccepted {
	return &UpdateOfferPriceAccepted{}
}

/*UpdateOfferPriceAccepted handles this case with default header values.

Accepted: Successfully scheduled the request for processing.
*/
type UpdateOfferPriceAccepted struct {
	Payload *models.ProcessStatus
}

func (o *UpdateOfferPriceAccepted) Error() string {
	return fmt.Sprintf("[PUT /retailer/offers/{offer-id}/price][%d] updateOfferPriceAccepted  %+v", 202, o.Payload)
}

func (o *UpdateOfferPriceAccepted) GetPayload() *models.ProcessStatus {
	return o.Payload
}

func (o *UpdateOfferPriceAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProcessStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateOfferPriceBadRequest creates a UpdateOfferPriceBadRequest with default headers values
func NewUpdateOfferPriceBadRequest() *UpdateOfferPriceBadRequest {
	return &UpdateOfferPriceBadRequest{}
}

/*UpdateOfferPriceBadRequest handles this case with default header values.

Bad request: The sent request does not meet the API specification. Please check the error message(s) for more information.
*/
type UpdateOfferPriceBadRequest struct {
	Payload *models.Problem
}

func (o *UpdateOfferPriceBadRequest) Error() string {
	return fmt.Sprintf("[PUT /retailer/offers/{offer-id}/price][%d] updateOfferPriceBadRequest  %+v", 400, o.Payload)
}

func (o *UpdateOfferPriceBadRequest) GetPayload() *models.Problem {
	return o.Payload
}

func (o *UpdateOfferPriceBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Problem)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
