// Code generated by go-swagger; DO NOT EDIT.

package shipments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new shipments API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for shipments API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	GetShipment(params *GetShipmentParams) (*GetShipmentOK, error)

	GetShipments(params *GetShipmentsParams) (*GetShipmentsOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  GetShipment gets a shipment by shipment id

  Retrieve a single shipment by its corresponding id.
*/
func (a *Client) GetShipment(params *GetShipmentParams) (*GetShipmentOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetShipmentParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "get-shipment",
		Method:             "GET",
		PathPattern:        "/retailer/shipments/{shipment-id}",
		ProducesMediaTypes: []string{"application/vnd.retailer.v3+json", "application/vnd.retailer.v3+xml"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetShipmentReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetShipmentOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for get-shipment: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetShipments gets shipment list

  A paginated list to retrieve all your shipments up to 3 months old. The shipments will be sorted by date in descending order.
*/
func (a *Client) GetShipments(params *GetShipmentsParams) (*GetShipmentsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetShipmentsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "get-shipments",
		Method:             "GET",
		PathPattern:        "/retailer/shipments",
		ProducesMediaTypes: []string{"application/vnd.retailer.v3+json", "application/vnd.retailer.v3+xml"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetShipmentsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetShipmentsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for get-shipments: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
