// Code generated by go-swagger; DO NOT EDIT.

package orders

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetOrdersParams creates a new GetOrdersParams object
// with the default values initialized.
func NewGetOrdersParams() *GetOrdersParams {
	var (
		fulfilmentMethodDefault = string("FBR")
		pageDefault             = int32(1)
	)
	return &GetOrdersParams{
		FulfilmentMethod: &fulfilmentMethodDefault,
		Page:             &pageDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetOrdersParamsWithTimeout creates a new GetOrdersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetOrdersParamsWithTimeout(timeout time.Duration) *GetOrdersParams {
	var (
		fulfilmentMethodDefault = string("FBR")
		pageDefault             = int32(1)
	)
	return &GetOrdersParams{
		FulfilmentMethod: &fulfilmentMethodDefault,
		Page:             &pageDefault,

		timeout: timeout,
	}
}

// NewGetOrdersParamsWithContext creates a new GetOrdersParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetOrdersParamsWithContext(ctx context.Context) *GetOrdersParams {
	var (
		fulfilmentMethodDefault = string("FBR")
		pageDefault             = int32(1)
	)
	return &GetOrdersParams{
		FulfilmentMethod: &fulfilmentMethodDefault,
		Page:             &pageDefault,

		Context: ctx,
	}
}

// NewGetOrdersParamsWithHTTPClient creates a new GetOrdersParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetOrdersParamsWithHTTPClient(client *http.Client) *GetOrdersParams {
	var (
		fulfilmentMethodDefault = string("FBR")
		pageDefault             = int32(1)
	)
	return &GetOrdersParams{
		FulfilmentMethod: &fulfilmentMethodDefault,
		Page:             &pageDefault,
		HTTPClient:       client,
	}
}

/*GetOrdersParams contains all the parameters to send to the API endpoint
for the get orders operation typically these are written to a http.Request
*/
type GetOrdersParams struct {

	/*FulfilmentMethod
	  The fulfilment method. Fulfilled by the retailer (FBR) or fulfilled by bol.com (FBB).

	*/
	FulfilmentMethod *string
	/*Page
	  The requested page number with a pagesize of 50

	*/
	Page *int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get orders params
func (o *GetOrdersParams) WithTimeout(timeout time.Duration) *GetOrdersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get orders params
func (o *GetOrdersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get orders params
func (o *GetOrdersParams) WithContext(ctx context.Context) *GetOrdersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get orders params
func (o *GetOrdersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get orders params
func (o *GetOrdersParams) WithHTTPClient(client *http.Client) *GetOrdersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get orders params
func (o *GetOrdersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFulfilmentMethod adds the fulfilmentMethod to the get orders params
func (o *GetOrdersParams) WithFulfilmentMethod(fulfilmentMethod *string) *GetOrdersParams {
	o.SetFulfilmentMethod(fulfilmentMethod)
	return o
}

// SetFulfilmentMethod adds the fulfilmentMethod to the get orders params
func (o *GetOrdersParams) SetFulfilmentMethod(fulfilmentMethod *string) {
	o.FulfilmentMethod = fulfilmentMethod
}

// WithPage adds the page to the get orders params
func (o *GetOrdersParams) WithPage(page *int32) *GetOrdersParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get orders params
func (o *GetOrdersParams) SetPage(page *int32) {
	o.Page = page
}

// WriteToRequest writes these params to a swagger request
func (o *GetOrdersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.FulfilmentMethod != nil {

		// query param fulfilment-method
		var qrFulfilmentMethod string
		if o.FulfilmentMethod != nil {
			qrFulfilmentMethod = *o.FulfilmentMethod
		}
		qFulfilmentMethod := qrFulfilmentMethod
		if qFulfilmentMethod != "" {
			if err := r.SetQueryParam("fulfilment-method", qFulfilmentMethod); err != nil {
				return err
			}
		}

	}

	if o.Page != nil {

		// query param page
		var qrPage int32
		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt32(qrPage)
		if qPage != "" {
			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
