// Code generated by go-swagger; DO NOT EDIT.

package inbounds

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/tcorp-bv/bol-api-go/models"
)

// NewGetProductLabelsParams creates a new GetProductLabelsParams object
// with the default values initialized.
func NewGetProductLabelsParams() *GetProductLabelsParams {
	var ()
	return &GetProductLabelsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetProductLabelsParamsWithTimeout creates a new GetProductLabelsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetProductLabelsParamsWithTimeout(timeout time.Duration) *GetProductLabelsParams {
	var ()
	return &GetProductLabelsParams{

		timeout: timeout,
	}
}

// NewGetProductLabelsParamsWithContext creates a new GetProductLabelsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetProductLabelsParamsWithContext(ctx context.Context) *GetProductLabelsParams {
	var ()
	return &GetProductLabelsParams{

		Context: ctx,
	}
}

// NewGetProductLabelsParamsWithHTTPClient creates a new GetProductLabelsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetProductLabelsParamsWithHTTPClient(client *http.Client) *GetProductLabelsParams {
	var ()
	return &GetProductLabelsParams{
		HTTPClient: client,
	}
}

/*GetProductLabelsParams contains all the parameters to send to the API endpoint
for the get product labels operation typically these are written to a http.Request
*/
type GetProductLabelsParams struct {

	/*Body*/
	Body *models.ProductLabelsRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get product labels params
func (o *GetProductLabelsParams) WithTimeout(timeout time.Duration) *GetProductLabelsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get product labels params
func (o *GetProductLabelsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get product labels params
func (o *GetProductLabelsParams) WithContext(ctx context.Context) *GetProductLabelsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get product labels params
func (o *GetProductLabelsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get product labels params
func (o *GetProductLabelsParams) WithHTTPClient(client *http.Client) *GetProductLabelsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get product labels params
func (o *GetProductLabelsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the get product labels params
func (o *GetProductLabelsParams) WithBody(body *models.ProductLabelsRequest) *GetProductLabelsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the get product labels params
func (o *GetProductLabelsParams) SetBody(body *models.ProductLabelsRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *GetProductLabelsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
