// Code generated by go-swagger; DO NOT EDIT.

package inbounds

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/tcorp-bv/bol-api-go/models"
)

// GetInboundReader is a Reader for the GetInbound structure.
type GetInboundReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetInboundReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetInboundOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetInboundBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetInboundNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetInboundOK creates a GetInboundOK with default headers values
func NewGetInboundOK() *GetInboundOK {
	return &GetInboundOK{}
}

/*GetInboundOK handles this case with default header values.

Ok: Successfully processed the request.
*/
type GetInboundOK struct {
	Payload *models.Inbound
}

func (o *GetInboundOK) Error() string {
	return fmt.Sprintf("[GET /retailer/inbounds/{inbound-id}][%d] getInboundOK  %+v", 200, o.Payload)
}

func (o *GetInboundOK) GetPayload() *models.Inbound {
	return o.Payload
}

func (o *GetInboundOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Inbound)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetInboundBadRequest creates a GetInboundBadRequest with default headers values
func NewGetInboundBadRequest() *GetInboundBadRequest {
	return &GetInboundBadRequest{}
}

/*GetInboundBadRequest handles this case with default header values.

Bad request: The sent request does not meet the API specification. Please check the error message(s) for more information.
*/
type GetInboundBadRequest struct {
	Payload *models.Problem
}

func (o *GetInboundBadRequest) Error() string {
	return fmt.Sprintf("[GET /retailer/inbounds/{inbound-id}][%d] getInboundBadRequest  %+v", 400, o.Payload)
}

func (o *GetInboundBadRequest) GetPayload() *models.Problem {
	return o.Payload
}

func (o *GetInboundBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Problem)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetInboundNotFound creates a GetInboundNotFound with default headers values
func NewGetInboundNotFound() *GetInboundNotFound {
	return &GetInboundNotFound{}
}

/*GetInboundNotFound handles this case with default header values.

Not found: The requested item could not be found.
*/
type GetInboundNotFound struct {
	Payload *models.Problem
}

func (o *GetInboundNotFound) Error() string {
	return fmt.Sprintf("[GET /retailer/inbounds/{inbound-id}][%d] getInboundNotFound  %+v", 404, o.Payload)
}

func (o *GetInboundNotFound) GetPayload() *models.Problem {
	return o.Payload
}

func (o *GetInboundNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Problem)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
