// Code generated by go-swagger; DO NOT EDIT.

package inbounds

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetInboundShippingLabelParams creates a new GetInboundShippingLabelParams object
// with the default values initialized.
func NewGetInboundShippingLabelParams() *GetInboundShippingLabelParams {
	var ()
	return &GetInboundShippingLabelParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetInboundShippingLabelParamsWithTimeout creates a new GetInboundShippingLabelParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetInboundShippingLabelParamsWithTimeout(timeout time.Duration) *GetInboundShippingLabelParams {
	var ()
	return &GetInboundShippingLabelParams{

		timeout: timeout,
	}
}

// NewGetInboundShippingLabelParamsWithContext creates a new GetInboundShippingLabelParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetInboundShippingLabelParamsWithContext(ctx context.Context) *GetInboundShippingLabelParams {
	var ()
	return &GetInboundShippingLabelParams{

		Context: ctx,
	}
}

// NewGetInboundShippingLabelParamsWithHTTPClient creates a new GetInboundShippingLabelParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetInboundShippingLabelParamsWithHTTPClient(client *http.Client) *GetInboundShippingLabelParams {
	var ()
	return &GetInboundShippingLabelParams{
		HTTPClient: client,
	}
}

/*GetInboundShippingLabelParams contains all the parameters to send to the API endpoint
for the get inbound shipping label operation typically these are written to a http.Request
*/
type GetInboundShippingLabelParams struct {

	/*InboundID
	  A unique identifier for an inbound shipment.

	*/
	InboundID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get inbound shipping label params
func (o *GetInboundShippingLabelParams) WithTimeout(timeout time.Duration) *GetInboundShippingLabelParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get inbound shipping label params
func (o *GetInboundShippingLabelParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get inbound shipping label params
func (o *GetInboundShippingLabelParams) WithContext(ctx context.Context) *GetInboundShippingLabelParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get inbound shipping label params
func (o *GetInboundShippingLabelParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get inbound shipping label params
func (o *GetInboundShippingLabelParams) WithHTTPClient(client *http.Client) *GetInboundShippingLabelParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get inbound shipping label params
func (o *GetInboundShippingLabelParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInboundID adds the inboundID to the get inbound shipping label params
func (o *GetInboundShippingLabelParams) WithInboundID(inboundID int64) *GetInboundShippingLabelParams {
	o.SetInboundID(inboundID)
	return o
}

// SetInboundID adds the inboundId to the get inbound shipping label params
func (o *GetInboundShippingLabelParams) SetInboundID(inboundID int64) {
	o.InboundID = inboundID
}

// WriteToRequest writes these params to a swagger request
func (o *GetInboundShippingLabelParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param inbound-id
	if err := r.SetPathParam("inbound-id", swag.FormatInt64(o.InboundID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
