// Code generated by go-swagger; DO NOT EDIT.

package inbounds

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/tcorp-bv/bol-api-go/models"
)

// GetInboundsReader is a Reader for the GetInbounds structure.
type GetInboundsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetInboundsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetInboundsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetInboundsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetInboundsOK creates a GetInboundsOK with default headers values
func NewGetInboundsOK() *GetInboundsOK {
	return &GetInboundsOK{}
}

/*GetInboundsOK handles this case with default header values.

Ok: Successfully processed the request.
*/
type GetInboundsOK struct {
	Payload *models.Inbounds
}

func (o *GetInboundsOK) Error() string {
	return fmt.Sprintf("[GET /retailer/inbounds][%d] getInboundsOK  %+v", 200, o.Payload)
}

func (o *GetInboundsOK) GetPayload() *models.Inbounds {
	return o.Payload
}

func (o *GetInboundsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Inbounds)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetInboundsBadRequest creates a GetInboundsBadRequest with default headers values
func NewGetInboundsBadRequest() *GetInboundsBadRequest {
	return &GetInboundsBadRequest{}
}

/*GetInboundsBadRequest handles this case with default header values.

Bad request: The sent request does not meet the API specification. Please check the error message(s) for more information.
*/
type GetInboundsBadRequest struct {
	Payload *models.Problem
}

func (o *GetInboundsBadRequest) Error() string {
	return fmt.Sprintf("[GET /retailer/inbounds][%d] getInboundsBadRequest  %+v", 400, o.Payload)
}

func (o *GetInboundsBadRequest) GetPayload() *models.Problem {
	return o.Payload
}

func (o *GetInboundsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Problem)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
