// Code generated by go-swagger; DO NOT EDIT.

package inbounds

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetPackingListParams creates a new GetPackingListParams object
// with the default values initialized.
func NewGetPackingListParams() *GetPackingListParams {
	var ()
	return &GetPackingListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetPackingListParamsWithTimeout creates a new GetPackingListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetPackingListParamsWithTimeout(timeout time.Duration) *GetPackingListParams {
	var ()
	return &GetPackingListParams{

		timeout: timeout,
	}
}

// NewGetPackingListParamsWithContext creates a new GetPackingListParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetPackingListParamsWithContext(ctx context.Context) *GetPackingListParams {
	var ()
	return &GetPackingListParams{

		Context: ctx,
	}
}

// NewGetPackingListParamsWithHTTPClient creates a new GetPackingListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetPackingListParamsWithHTTPClient(client *http.Client) *GetPackingListParams {
	var ()
	return &GetPackingListParams{
		HTTPClient: client,
	}
}

/*GetPackingListParams contains all the parameters to send to the API endpoint
for the get packing list operation typically these are written to a http.Request
*/
type GetPackingListParams struct {

	/*InboundID
	  A unique identifier for an inbound shipment.

	*/
	InboundID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get packing list params
func (o *GetPackingListParams) WithTimeout(timeout time.Duration) *GetPackingListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get packing list params
func (o *GetPackingListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get packing list params
func (o *GetPackingListParams) WithContext(ctx context.Context) *GetPackingListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get packing list params
func (o *GetPackingListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get packing list params
func (o *GetPackingListParams) WithHTTPClient(client *http.Client) *GetPackingListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get packing list params
func (o *GetPackingListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInboundID adds the inboundID to the get packing list params
func (o *GetPackingListParams) WithInboundID(inboundID int64) *GetPackingListParams {
	o.SetInboundID(inboundID)
	return o
}

// SetInboundID adds the inboundId to the get packing list params
func (o *GetPackingListParams) SetInboundID(inboundID int64) {
	o.InboundID = inboundID
}

// WriteToRequest writes these params to a swagger request
func (o *GetPackingListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param inbound-id
	if err := r.SetPathParam("inbound-id", swag.FormatInt64(o.InboundID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
