// Code generated by go-swagger; DO NOT EDIT.

package inbounds

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetInboundParams creates a new GetInboundParams object
// with the default values initialized.
func NewGetInboundParams() *GetInboundParams {
	var ()
	return &GetInboundParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetInboundParamsWithTimeout creates a new GetInboundParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetInboundParamsWithTimeout(timeout time.Duration) *GetInboundParams {
	var ()
	return &GetInboundParams{

		timeout: timeout,
	}
}

// NewGetInboundParamsWithContext creates a new GetInboundParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetInboundParamsWithContext(ctx context.Context) *GetInboundParams {
	var ()
	return &GetInboundParams{

		Context: ctx,
	}
}

// NewGetInboundParamsWithHTTPClient creates a new GetInboundParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetInboundParamsWithHTTPClient(client *http.Client) *GetInboundParams {
	var ()
	return &GetInboundParams{
		HTTPClient: client,
	}
}

/*GetInboundParams contains all the parameters to send to the API endpoint
for the get inbound operation typically these are written to a http.Request
*/
type GetInboundParams struct {

	/*InboundID
	  A unique identifier for an inbound shipment.

	*/
	InboundID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get inbound params
func (o *GetInboundParams) WithTimeout(timeout time.Duration) *GetInboundParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get inbound params
func (o *GetInboundParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get inbound params
func (o *GetInboundParams) WithContext(ctx context.Context) *GetInboundParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get inbound params
func (o *GetInboundParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get inbound params
func (o *GetInboundParams) WithHTTPClient(client *http.Client) *GetInboundParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get inbound params
func (o *GetInboundParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInboundID adds the inboundID to the get inbound params
func (o *GetInboundParams) WithInboundID(inboundID int64) *GetInboundParams {
	o.SetInboundID(inboundID)
	return o
}

// SetInboundID adds the inboundId to the get inbound params
func (o *GetInboundParams) SetInboundID(inboundID int64) {
	o.InboundID = inboundID
}

// WriteToRequest writes these params to a swagger request
func (o *GetInboundParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param inbound-id
	if err := r.SetPathParam("inbound-id", swag.FormatInt64(o.InboundID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
