// Code generated by go-swagger; DO NOT EDIT.

package returns

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/tcorp-bv/bol-api-go/models"
)

// GetReturnsReader is a Reader for the GetReturns structure.
type GetReturnsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetReturnsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetReturnsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetReturnsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetReturnsOK creates a GetReturnsOK with default headers values
func NewGetReturnsOK() *GetReturnsOK {
	return &GetReturnsOK{}
}

/*GetReturnsOK handles this case with default header values.

Ok: Successfully processed the request.
*/
type GetReturnsOK struct {
	Payload *models.ReturnsResponse
}

func (o *GetReturnsOK) Error() string {
	return fmt.Sprintf("[GET /retailer/returns][%d] getReturnsOK  %+v", 200, o.Payload)
}

func (o *GetReturnsOK) GetPayload() *models.ReturnsResponse {
	return o.Payload
}

func (o *GetReturnsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ReturnsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetReturnsBadRequest creates a GetReturnsBadRequest with default headers values
func NewGetReturnsBadRequest() *GetReturnsBadRequest {
	return &GetReturnsBadRequest{}
}

/*GetReturnsBadRequest handles this case with default header values.

Bad request: The sent request does not meet the API specification. Please check the error message(s) for more information.
*/
type GetReturnsBadRequest struct {
	Payload *models.Problem
}

func (o *GetReturnsBadRequest) Error() string {
	return fmt.Sprintf("[GET /retailer/returns][%d] getReturnsBadRequest  %+v", 400, o.Payload)
}

func (o *GetReturnsBadRequest) GetPayload() *models.Problem {
	return o.Payload
}

func (o *GetReturnsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Problem)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
