// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AddressDetails The address details where this order needs to be shipped to. This can be the customers' own address, a (company) business address or a Pick Up Point address.
//
// swagger:model AddressDetails
type AddressDetails struct {

	// The supplement belonging to the address.
	AddressSupplement string `json:"addressSupplement,omitempty"`

	// The chamber of commerce number of the account that placed the order.
	ChamberOfCommerceNumber string `json:"chamberOfCommerceNumber,omitempty"`

	// The name of the city.
	City string `json:"city,omitempty"`

	// The company name.
	Company string `json:"company,omitempty"`

	// The country code.
	CountryCode string `json:"countryCode,omitempty"`

	// The delivery phone number of the customer. Filled in case the order requires an appointment for delivering the goods.
	DeliveryPhoneNumber string `json:"deliveryPhoneNumber,omitempty"`

	// A scrambled email address that can be used to contact the customer.
	Email string `json:"email,omitempty"`

	// Additional information related to the address that helps in delivering the package.
	ExtraAddressInformation string `json:"extraAddressInformation,omitempty"`

	// The first name of the customer.
	FirstName string `json:"firstName,omitempty"`

	// The house number.
	HouseNumber string `json:"houseNumber,omitempty"`

	// The extension on the house number.
	HouseNumberExtended string `json:"houseNumberExtended,omitempty"`

	// The order reference specified by the customer when ordering a product.
	OrderReference string `json:"orderReference,omitempty"`

	// The name of Pick Up Point location this order needs to be shipped to.
	PickUpPointName string `json:"pickUpPointName,omitempty"`

	// The salutation of the customer (01 = MALE, 02 = FEMALE, 03 = UNKNOWN)
	SalutationCode string `json:"salutationCode,omitempty"`

	// The street name.
	StreetName string `json:"streetName,omitempty"`

	// The surname of the customer.
	SurName string `json:"surName,omitempty"`

	// The VAT number.
	VatNumber string `json:"vatNumber,omitempty"`

	// The ZIP code.
	ZipCode string `json:"zipCode,omitempty"`
}

// Validate validates this address details
func (m *AddressDetails) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AddressDetails) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AddressDetails) UnmarshalBinary(b []byte) error {
	var res AddressDetails
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
