// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DeliveryWindowsForInboundShipments delivery windows for inbound shipments
//
// swagger:model Delivery windows for inbound shipments.
type DeliveryWindowsForInboundShipments struct {

	// An available timeslot to be reserved for inbound shipments.
	TimeSlots []*TimeSlot `json:"timeSlots"`
}

// Validate validates this delivery windows for inbound shipments
func (m *DeliveryWindowsForInboundShipments) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTimeSlots(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DeliveryWindowsForInboundShipments) validateTimeSlots(formats strfmt.Registry) error {

	if swag.IsZero(m.TimeSlots) { // not required
		return nil
	}

	for i := 0; i < len(m.TimeSlots); i++ {
		if swag.IsZero(m.TimeSlots[i]) { // not required
			continue
		}

		if m.TimeSlots[i] != nil {
			if err := m.TimeSlots[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("timeSlots" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *DeliveryWindowsForInboundShipments) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeliveryWindowsForInboundShipments) UnmarshalBinary(b []byte) error {
	var res DeliveryWindowsForInboundShipments
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
