// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Inbounds inbounds
//
// swagger:model Inbounds
type Inbounds struct {

	// An inbound shipment.
	// Required: true
	Inbounds []*Inbound `json:"inbounds"`
}

// Validate validates this inbounds
func (m *Inbounds) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateInbounds(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Inbounds) validateInbounds(formats strfmt.Registry) error {

	if err := validate.Required("inbounds", "body", m.Inbounds); err != nil {
		return err
	}

	for i := 0; i < len(m.Inbounds); i++ {
		if swag.IsZero(m.Inbounds[i]) { // not required
			continue
		}

		if m.Inbounds[i] != nil {
			if err := m.Inbounds[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("inbounds" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *Inbounds) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Inbounds) UnmarshalBinary(b []byte) error {
	var res Inbounds
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
