// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// InboundProductRequest inbound product request
//
// swagger:model InboundProductRequest
type InboundProductRequest struct {

	// The number of announced items.
	AnnouncedQuantity int32 `json:"announcedQuantity,omitempty"`

	// Warning: This field is deprecated. Any value given will be overrided with the bsku known by bol.com.
	Bsku string `json:"bsku,omitempty"`

	// The EAN number associated with this product.
	Ean string `json:"ean,omitempty"`

	// The number of received items.
	ReceivedQuantity int32 `json:"receivedQuantity,omitempty"`

	// The current state of the inbound product.
	// Enum: [Announced Unannounced Unknown]
	State string `json:"state,omitempty"`
}

// Validate validates this inbound product request
func (m *InboundProductRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateState(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var inboundProductRequestTypeStatePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["Announced","Unannounced","Unknown"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		inboundProductRequestTypeStatePropEnum = append(inboundProductRequestTypeStatePropEnum, v)
	}
}

const (

	// InboundProductRequestStateAnnounced captures enum value "Announced"
	InboundProductRequestStateAnnounced string = "Announced"

	// InboundProductRequestStateUnannounced captures enum value "Unannounced"
	InboundProductRequestStateUnannounced string = "Unannounced"

	// InboundProductRequestStateUnknown captures enum value "Unknown"
	InboundProductRequestStateUnknown string = "Unknown"
)

// prop value enum
func (m *InboundProductRequest) validateStateEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, inboundProductRequestTypeStatePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *InboundProductRequest) validateState(formats strfmt.Registry) error {

	if swag.IsZero(m.State) { // not required
		return nil
	}

	// value enum
	if err := m.validateStateEnum("state", "body", m.State); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *InboundProductRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InboundProductRequest) UnmarshalBinary(b []byte) error {
	var res InboundProductRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
