// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// InventoryResponse inventory response
//
// swagger:model InventoryResponse
type InventoryResponse struct {

	// offers
	// Required: true
	Offers []*InventoryOffer `json:"offers"`
}

// Validate validates this inventory response
func (m *InventoryResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOffers(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InventoryResponse) validateOffers(formats strfmt.Registry) error {

	if err := validate.Required("offers", "body", m.Offers); err != nil {
		return err
	}

	for i := 0; i < len(m.Offers); i++ {
		if swag.IsZero(m.Offers[i]) { // not required
			continue
		}

		if m.Offers[i] != nil {
			if err := m.Offers[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("offers" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *InventoryResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InventoryResponse) UnmarshalBinary(b []byte) error {
	var res InventoryResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
