// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// InventoryOffer inventory offer
//
// swagger:model InventoryOffer
type InventoryOffer struct {

	// The BSKU number associated with this product.
	Bsku string `json:"bsku,omitempty"`

	// The EAN number associated with this product.
	Ean string `json:"ean,omitempty"`

	// The stock that is not available for sale anymore (unsaleable)
	NckStock int32 `json:"nckStock,omitempty"`

	// The stock that is available for sale (saleable).
	Stock int32 `json:"stock,omitempty"`

	// The product title.
	Title string `json:"title,omitempty"`
}

// Validate validates this inventory offer
func (m *InventoryOffer) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *InventoryOffer) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InventoryOffer) UnmarshalBinary(b []byte) error {
	var res InventoryOffer
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
