// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Norm norm
//
// swagger:model Norm
type Norm struct {

	// Condition norm for this indicator.
	Condition string `json:"condition,omitempty"`

	// Service norm for this indicator.
	Value float32 `json:"value,omitempty"`
}

// Validate validates this norm
func (m *Norm) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Norm) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Norm) UnmarshalBinary(b []byte) error {
	var res Norm
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
