// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// OrderCustomerDetails Customer details of the order.
//
// swagger:model OrderCustomerDetails
type OrderCustomerDetails struct {

	// billing details
	// Required: true
	BillingDetails *AddressDetails `json:"billingDetails"`

	// shipment details
	// Required: true
	ShipmentDetails *AddressDetails `json:"shipmentDetails"`
}

// Validate validates this order customer details
func (m *OrderCustomerDetails) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBillingDetails(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateShipmentDetails(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OrderCustomerDetails) validateBillingDetails(formats strfmt.Registry) error {

	if err := validate.Required("billingDetails", "body", m.BillingDetails); err != nil {
		return err
	}

	if m.BillingDetails != nil {
		if err := m.BillingDetails.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("billingDetails")
			}
			return err
		}
	}

	return nil
}

func (m *OrderCustomerDetails) validateShipmentDetails(formats strfmt.Registry) error {

	if err := validate.Required("shipmentDetails", "body", m.ShipmentDetails); err != nil {
		return err
	}

	if m.ShipmentDetails != nil {
		if err := m.ShipmentDetails.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("shipmentDetails")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *OrderCustomerDetails) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrderCustomerDetails) UnmarshalBinary(b []byte) error {
	var res OrderCustomerDetails
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
