// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PerformanceIndicators performance indicators
//
// swagger:model PerformanceIndicators
type PerformanceIndicators struct {

	// performance indicators
	// Required: true
	PerformanceIndicators []*PerformanceIndicator `json:"performanceIndicators"`
}

// Validate validates this performance indicators
func (m *PerformanceIndicators) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePerformanceIndicators(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PerformanceIndicators) validatePerformanceIndicators(formats strfmt.Registry) error {

	if err := validate.Required("performanceIndicators", "body", m.PerformanceIndicators); err != nil {
		return err
	}

	for i := 0; i < len(m.PerformanceIndicators); i++ {
		if swag.IsZero(m.PerformanceIndicators[i]) { // not required
			continue
		}

		if m.PerformanceIndicators[i] != nil {
			if err := m.PerformanceIndicators[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("performanceIndicators" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *PerformanceIndicators) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PerformanceIndicators) UnmarshalBinary(b []byte) error {
	var res PerformanceIndicators
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
