// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ProcessStatusResponse process status response
//
// swagger:model ProcessStatusResponse
type ProcessStatusResponse struct {

	// process statuses
	// Required: true
	ProcessStatuses []*ProcessStatus `json:"processStatuses"`
}

// Validate validates this process status response
func (m *ProcessStatusResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateProcessStatuses(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ProcessStatusResponse) validateProcessStatuses(formats strfmt.Registry) error {

	if err := validate.Required("processStatuses", "body", m.ProcessStatuses); err != nil {
		return err
	}

	for i := 0; i < len(m.ProcessStatuses); i++ {
		if swag.IsZero(m.ProcessStatuses[i]) { // not required
			continue
		}

		if m.ProcessStatuses[i] != nil {
			if err := m.ProcessStatuses[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("processStatuses" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ProcessStatusResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProcessStatusResponse) UnmarshalBinary(b []byte) error {
	var res ProcessStatusResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
