// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Product product
//
// swagger:model Product
type Product struct {

	// The number of announced items.
	AnnouncedQuantity int32 `json:"announcedQuantity,omitempty"`

	// The BSKU number associated with this product.
	Bsku string `json:"bsku,omitempty"`

	// The EAN number associated with this product.
	Ean string `json:"ean,omitempty"`

	// The number of received items.
	ReceivedQuantity int32 `json:"receivedQuantity,omitempty"`

	// The current state of the inbound product.
	// Enum: [Announced Unannounced Unknown]
	State string `json:"state,omitempty"`
}

// Validate validates this product
func (m *Product) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateState(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var productTypeStatePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["Announced","Unannounced","Unknown"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		productTypeStatePropEnum = append(productTypeStatePropEnum, v)
	}
}

const (

	// ProductStateAnnounced captures enum value "Announced"
	ProductStateAnnounced string = "Announced"

	// ProductStateUnannounced captures enum value "Unannounced"
	ProductStateUnannounced string = "Unannounced"

	// ProductStateUnknown captures enum value "Unknown"
	ProductStateUnknown string = "Unknown"
)

// prop value enum
func (m *Product) validateStateEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, productTypeStatePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *Product) validateState(formats strfmt.Registry) error {

	if swag.IsZero(m.State) { // not required
		return nil
	}

	// value enum
	if err := m.validateStateEnum("state", "body", m.State); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Product) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Product) UnmarshalBinary(b []byte) error {
	var res Product
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
