// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ProductLabel product label
//
// swagger:model ProductLabel
type ProductLabel struct {

	// The EAN number associated with this product.
	// Required: true
	Ean *string `json:"ean"`

	// Number of products to generate labels for.
	// Required: true
	Quantity *int32 `json:"quantity"`
}

// Validate validates this product label
func (m *ProductLabel) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEan(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateQuantity(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ProductLabel) validateEan(formats strfmt.Registry) error {

	if err := validate.Required("ean", "body", m.Ean); err != nil {
		return err
	}

	return nil
}

func (m *ProductLabel) validateQuantity(formats strfmt.Registry) error {

	if err := validate.Required("quantity", "body", m.Quantity); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ProductLabel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProductLabel) UnmarshalBinary(b []byte) error {
	var res ProductLabel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
