// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ReducedOrderItem An order item.
//
// swagger:model ReducedOrderItem
type ReducedOrderItem struct {

	// Indicates whether the order was cancelled on request of the customer before the retailer has shipped it.
	CancelRequest bool `json:"cancelRequest,omitempty"`

	// The EAN number associated with this product.
	Ean string `json:"ean,omitempty"`

	// The id for the order item (1 order can have multiple order items).
	OrderItemID string `json:"orderItemId,omitempty"`

	// Amount of ordered products for this order item id.
	Quantity int32 `json:"quantity,omitempty"`
}

// Validate validates this reduced order item
func (m *ReducedOrderItem) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ReducedOrderItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ReducedOrderItem) UnmarshalBinary(b []byte) error {
	var res ReducedOrderItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
