// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RetailerOffer retailer offer
//
// swagger:model RetailerOffer
type RetailerOffer struct {

	// condition
	// Required: true
	Condition *Condition `json:"condition"`

	// The EAN number associated with this product. Note: in case an ISBN is provided, the ISBN will be replaced with the actual EAN belonging to this ISBN.
	Ean string `json:"ean,omitempty"`

	// fulfilment
	// Required: true
	Fulfilment *Fulfilment `json:"fulfilment"`

	// not publishable reasons
	// Required: true
	NotPublishableReasons []*NotPublishableReason `json:"notPublishableReasons"`

	// Unique identifier for an offer.
	OfferID string `json:"offerId,omitempty"`

	// Indicates whether or not you want to put this offer for sale on the bol.com website. Defaults to false.
	OnHoldByRetailer bool `json:"onHoldByRetailer,omitempty"`

	// pricing
	// Required: true
	Pricing *Pricing `json:"pricing"`

	// A user-defined reference that helps you identify this particular offer when receiving data from us. This element can optionally be left empty and has a maximum amount of 20 characters.
	ReferenceCode string `json:"referenceCode,omitempty"`

	// stock
	// Required: true
	Stock *Stock `json:"stock"`

	// store
	// Required: true
	Store *Store `json:"store"`

	// In case the item is not known to bol.com you can use this field to identify this particular product. Note: in case the product is known to bol.com, the unknown product title will not be stored.
	UnknownProductTitle string `json:"unknownProductTitle,omitempty"`
}

// Validate validates this retailer offer
func (m *RetailerOffer) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCondition(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFulfilment(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNotPublishableReasons(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePricing(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStock(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStore(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RetailerOffer) validateCondition(formats strfmt.Registry) error {

	if err := validate.Required("condition", "body", m.Condition); err != nil {
		return err
	}

	if m.Condition != nil {
		if err := m.Condition.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("condition")
			}
			return err
		}
	}

	return nil
}

func (m *RetailerOffer) validateFulfilment(formats strfmt.Registry) error {

	if err := validate.Required("fulfilment", "body", m.Fulfilment); err != nil {
		return err
	}

	if m.Fulfilment != nil {
		if err := m.Fulfilment.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("fulfilment")
			}
			return err
		}
	}

	return nil
}

func (m *RetailerOffer) validateNotPublishableReasons(formats strfmt.Registry) error {

	if err := validate.Required("notPublishableReasons", "body", m.NotPublishableReasons); err != nil {
		return err
	}

	for i := 0; i < len(m.NotPublishableReasons); i++ {
		if swag.IsZero(m.NotPublishableReasons[i]) { // not required
			continue
		}

		if m.NotPublishableReasons[i] != nil {
			if err := m.NotPublishableReasons[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("notPublishableReasons" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *RetailerOffer) validatePricing(formats strfmt.Registry) error {

	if err := validate.Required("pricing", "body", m.Pricing); err != nil {
		return err
	}

	if m.Pricing != nil {
		if err := m.Pricing.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("pricing")
			}
			return err
		}
	}

	return nil
}

func (m *RetailerOffer) validateStock(formats strfmt.Registry) error {

	if err := validate.Required("stock", "body", m.Stock); err != nil {
		return err
	}

	if m.Stock != nil {
		if err := m.Stock.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("stock")
			}
			return err
		}
	}

	return nil
}

func (m *RetailerOffer) validateStore(formats strfmt.Registry) error {

	if err := validate.Required("store", "body", m.Store); err != nil {
		return err
	}

	if m.Store != nil {
		if err := m.Store.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("store")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *RetailerOffer) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RetailerOffer) UnmarshalBinary(b []byte) error {
	var res RetailerOffer
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
