// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ReturnsResponse returns response
//
// swagger:model ReturnsResponse
type ReturnsResponse struct {

	// returns
	// Required: true
	Returns []*ReducedReturnItem `json:"returns"`
}

// Validate validates this returns response
func (m *ReturnsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateReturns(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ReturnsResponse) validateReturns(formats strfmt.Registry) error {

	if err := validate.Required("returns", "body", m.Returns); err != nil {
		return err
	}

	for i := 0; i < len(m.Returns); i++ {
		if swag.IsZero(m.Returns[i]) { // not required
			continue
		}

		if m.Returns[i] != nil {
			if err := m.Returns[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("returns" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ReturnsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ReturnsResponse) UnmarshalBinary(b []byte) error {
	var res ReturnsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
