// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Score The score for this measurement. In case there are no scores for an indicator, this element is omitted from the response.
//
// swagger:model Score
type Score struct {

	// Indicates whether the score conforms to the bol.com service norm or not.
	Conforms bool `json:"conforms,omitempty"`

	// The lower part of the fraction (below the line). This usually is the larger number compared to the the numerator.
	Denominator int32 `json:"denominator,omitempty"`

	// The difference between the score and the bol.com service norm.
	DistanceToNorm float32 `json:"distanceToNorm,omitempty"`

	// The top part of the fraction (above the line). This usually is the smaller number compared to the denominator.
	Numerator int32 `json:"numerator,omitempty"`

	// The score for this measurement (denominator divided by the numerator).
	Value float32 `json:"value,omitempty"`
}

// Validate validates this score
func (m *Score) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Score) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Score) UnmarshalBinary(b []byte) error {
	var res Score
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
