// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Transport transport
//
// swagger:model Transport
type Transport struct {

	// A unique code referring to the used shipping label for this shipment.
	ShippingLabelCode string `json:"shippingLabelCode,omitempty"`

	// Warning: This field is deprecated. See API release notes for more information.
	ShippingLabelID int64 `json:"shippingLabelId,omitempty"`

	// The track and trace code that is associated with this transport.
	TrackAndTrace string `json:"trackAndTrace,omitempty"`

	// The transport id.
	TransportID int64 `json:"transportId,omitempty"`

	// Specify the transporter that will carry out the shipment.
	TransporterCode string `json:"transporterCode,omitempty"`
}

// Validate validates this transport
func (m *Transport) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Transport) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Transport) UnmarshalBinary(b []byte) error {
	var res Transport
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
