// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TransportersResponse transporters response
//
// swagger:model TransportersResponse
type TransportersResponse struct {

	// fbb transporters
	// Required: true
	// Read Only: true
	FbbTransporters []*Transporter `json:"fbbTransporters"`
}

// Validate validates this transporters response
func (m *TransportersResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFbbTransporters(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TransportersResponse) validateFbbTransporters(formats strfmt.Registry) error {

	if err := validate.Required("fbbTransporters", "body", m.FbbTransporters); err != nil {
		return err
	}

	for i := 0; i < len(m.FbbTransporters); i++ {
		if swag.IsZero(m.FbbTransporters[i]) { // not required
			continue
		}

		if m.FbbTransporters[i] != nil {
			if err := m.FbbTransporters[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("fbbTransporters" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *TransportersResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TransportersResponse) UnmarshalBinary(b []byte) error {
	var res TransportersResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
