// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UpdateOfferPriceRequest update offer price request
//
// swagger:model UpdateOfferPriceRequest
type UpdateOfferPriceRequest struct {

	// pricing
	// Required: true
	Pricing *Pricing `json:"pricing"`
}

// Validate validates this update offer price request
func (m *UpdateOfferPriceRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePricing(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UpdateOfferPriceRequest) validatePricing(formats strfmt.Registry) error {

	if err := validate.Required("pricing", "body", m.Pricing); err != nil {
		return err
	}

	if m.Pricing != nil {
		if err := m.Pricing.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("pricing")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *UpdateOfferPriceRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateOfferPriceRequest) UnmarshalBinary(b []byte) error {
	var res UpdateOfferPriceRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
