// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Violation Describes a violation that occurred interacting with the API.
//
// swagger:model Violation
type Violation struct {

	// Describes the origin of the error, for instance a field or query parameter validation error.
	Name string `json:"name,omitempty"`

	// Detailed description of the validation error that caused the problem.
	Reason string `json:"reason,omitempty"`
}

// Validate validates this violation
func (m *Violation) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Violation) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Violation) UnmarshalBinary(b []byte) error {
	var res Violation
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
